workflows:
  JNI Libs macOS silicone:
    name: build-macos-jni-artifact
    instance_type: mac_mini_m1
    environment:
      java: 17
#    triggering:
#      events:
#        - push
#        - pull_request
    scripts:

        - |
          ls -al
          id
          pwd
          ./ci_scripts/java_jni_lib_macos.sh

        - pwd
        - find . -name 'libjni_notifications.jnilib'
        - ls -al /Users/builder/clone/libjni_notifications.jnilib
        - mv -v /Users/builder/clone/libjni_notifications.jnilib /Users/builder/clone/libjni_notifications_arm64.jnilib

    artifacts:
      - /Users/builder/clone/libjni_notifications_arm64.jnilib
